#!/bin/bash

#$ -S /bin/bash     # run job as a Bash shell [IMPORTANT]
#$ -cwd             # run job in the current working directory

# Use this email address:
#$ -M isobel.beasley@ucsf.edu

# Send yourself an email when the job:
# aborts abnormally (fails), begins, and ends successfully
#$ -m abe

# Multithreaded (SMP) job: must run on one node 
#$ -pe smp 1

# The name of the job:
#$ -N thous_genomes

# How much RAM per slot
#$ -l mem_free=1G

#$ -l scratch=2G      # job requires up to 2 GiB of local /scratch space

# The maximum running time of the job in hours:mins:sec (converted to 10 minutes):
#$ -l h_rt=0:10:00

# Partition for the job (SGE equivalent is specifying the queue):
#$ -q short.q

# Check that the script is launched with qsub
if [ "x$JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with qsub"
   exit 1
fi

module load CBI
module load htslib/1.21
module load bcftools 

cd data

# wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20181203_biallelic_SNV/ALL.chr20.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz.tbi

# now ... let's get the thousand genomes vcf for chromosome 20 
wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20181203_biallelic_SNV/ALL.chr20.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz 

gunzip ALL.chr20.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz

bcftools view ALL.chr20.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf -s HG00096 -O b -o chrom_20_HG00096.bcf

bcftools head chrom_20_HG00096.bcf -n 10

chrom_20_HG00096.bcf
