#!/bin/bash

#$ -S /bin/bash     # run job as a Bash shell [IMPORTANT]
#$ -cwd             # run job in the current working directory

# Use this email address:
#$ -M isobel.beasley@ucsf.edu

# Send yourself an email when the job:
# aborts abnormally (fails), begins, and ends successfully
#$ -m abe

# Multithreaded (SMP) job: must run on one node 
#$ -pe smp 1

# The name of the job:
#$ -N test_tsinfer

# How much RAM per slot
#$ -l mem_free=1G

#$ -l scratch=2G      # job requires up to 2 GiB of local /scratch space

# The maximum running time of the job in hours:mins:sec (converted to 10 minutes):
#$ -l h_rt=0:10:00

# Partition for the job (SGE equivalent is specifying the queue):
#$ -q short.q

# Check that the script is launched with qsub
if [ "x$JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with qsub"
   exit 1
fi

module load CBI
module load miniforge3/24.7.1-0
conda activate admixture_arg_env

python3 code/ts_prep.py